# This workflow triggers a complete test suite run,
# coverage validation checks and pushes data to sonarcloud
# whenever a PR is made against main branch.
# The file is called `ready-to-merge`. What else did you expect it would do ? !

name: Ready to Merge Workflow

on:
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches:
      - "main"

jobs:
  ci-build:
    runs-on: ubuntu-latest
    steps:
      - name: Source code checkout
        uses: actions/checkout@v3
      - name: Cache gradle dependencies
        uses: actions/cache@v2.1.6
        with:
          path: |
            ~/.gradle/caches
            ~//gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'zulu'
      - name: Run test suite and coverage
        run: chmod +x ./gradlew && ./gradlew test
